################################################################################
# Automatically-generated file. Do not edit!
################################################################################

DLD_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
COM_WINDRIVER_CDT_DIAB_OUTPUTTYPE_LINKER_MAP_OUTPUTS := 
EXECUTABLES := 
WPODIR := 
OBJS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ASW/App_SWC/ASW_RTE \
ASW/App_SWC/Common \
ASW/App_SWC/Modules/EACC \
ASW/App_SWC/Modules/EACM \
ASW/App_SWC/Modules/EACT \
ASW/App_SWC/Modules/EAMM \
ASW/App_SWC/Modules/EBCR \
ASW/App_SWC/Modules/EBCS \
ASW/App_SWC/Modules/EBIM \
ASW/App_SWC/Modules/ECCR \
ASW/App_SWC/Modules/ECCS \
ASW/App_SWC/Modules/ECEC \
ASW/App_SWC/Modules/ECHM \
ASW/App_SWC/Modules/ECIM \
ASW/App_SWC/Modules/ECMM \
ASW/App_SWC/Modules/ECTC \
ASW/App_SWC/Modules/ECTD \
ASW/App_SWC/Modules/EDCC \
ASW/App_SWC/Modules/EETM \
ASW/App_SWC/Modules/EHCR \
ASW/App_SWC/Modules/EHCS \
ASW/App_SWC/Modules/EHVS \
ASW/App_SWC/Modules/EISO \
ASW/App_SWC/Modules/ELED \
ASW/App_SWC/Modules/EMSM \
ASW/App_SWC/Modules/ETCR \
ASW/App_SWC/Modules/ETCS \
ASW/App_SWC/Modules/ETIM \
ASW/Asw_SWC/src \
ASW/Diag_SWC/src \
ASW/NvM_SWC/src \
ASW/Os_SWC/src \
ASW/WdgM_SWC/src \
ASW/Xcp_SWC/src/App \
ASW/Xcp_SWC/src \
BSW/integration/src \
BSW/integration/src/DcmAppl \
BSW/src/BSW/Gen/Bfx/src \
BSW/src/BSW/Gen/BswM \
BSW/src/BSW/Gen/BswM/src \
BSW/src/BSW/Gen/CanIf \
BSW/src/BSW/Gen/CanIf/src \
BSW/src/BSW/Gen/CanSM \
BSW/src/BSW/Gen/CanSM/src \
BSW/src/BSW/Gen/CanTp \
BSW/src/BSW/Gen/CanTp/src \
BSW/src/BSW/Gen/Com \
BSW/src/BSW/Gen/Com/src \
BSW/src/BSW/Gen/ComM \
BSW/src/BSW/Gen/ComM/src \
BSW/src/BSW/Gen/Crc \
BSW/src/BSW/Gen/Dcm \
BSW/src/BSW/Gen/Dcm/src \
BSW/src/BSW/Gen/Dem \
BSW/src/BSW/Gen/Dem/src \
BSW/src/BSW/Gen/Det/src \
BSW/src/BSW/Gen/Ea \
BSW/src/BSW/Gen/Ea/src \
BSW/src/BSW/Gen/EcuM \
BSW/src/BSW/Gen/EcuM/src \
BSW/src/BSW/Gen/EthIf \
BSW/src/BSW/Gen/EthIf/src \
BSW/src/BSW/Gen/EthSM \
BSW/src/BSW/Gen/EthSM/src \
BSW/src/BSW/Gen/EthTrcv \
BSW/src/BSW/Gen/EthTrcv/src \
BSW/src/BSW/Gen/Fee \
BSW/src/BSW/Gen/Fee/src \
BSW/src/BSW/Gen/FiM \
BSW/src/BSW/Gen/FiM/src \
BSW/src/BSW/Gen/IpduM \
BSW/src/BSW/Gen/IpduM/src \
BSW/src/BSW/Gen/MemIf/src \
BSW/src/BSW/Gen/NvM \
BSW/src/BSW/Gen/NvM/src \
BSW/src/BSW/Gen/PduR \
BSW/src/BSW/Gen/PduR/src \
BSW/src/BSW/Gen/Rba_DiagLib/src \
BSW/src/BSW/Gen/Rba_EthArp \
BSW/src/BSW/Gen/Rba_EthArp/src \
BSW/src/BSW/Gen/Rba_EthICMP \
BSW/src/BSW/Gen/Rba_EthICMP/src \
BSW/src/BSW/Gen/Rba_EthIPv4 \
BSW/src/BSW/Gen/Rba_EthIPv4/src \
BSW/src/BSW/Gen/Rba_EthTcp \
BSW/src/BSW/Gen/Rba_EthTcp/src \
BSW/src/BSW/Gen/Rba_EthUdp \
BSW/src/BSW/Gen/Rba_EthUdp/src \
BSW/src/BSW/Gen/Rba_FeeFs1/src \
BSW/src/BSW/Gen/SoAd \
BSW/src/BSW/Gen/SoAd/src \
BSW/src/BSW/Gen/TcpIp \
BSW/src/BSW/Gen/TcpIp/src \
BSW/src/BSW/Gen/WdgIf \
BSW/src/BSW/Gen/WdgM \
BSW/src/BSW/Gen/WdgM/src \
BSW/src/BSW/Gen/Xcp \
BSW/src/BSW/Gen/Xcp/src \
CDD/CCV \
CDD/ComAb \
CDD/DCDC \
CDD/DP83822 \
CDD/Diag \
CDD/EthComm \
CDD/Fls \
CDD/IoAb \
CDD/M95640 \
CDD/M95640/Flash_drv \
CDD/McanComm \
CDD/PowerEnergyMeter \
CDD/SJA1105 \
CDD/TBOXComm \
CDD/TJA1101 \
CDD/TPanel \
CDD/common \
CDD/esci \
CDD/mtcard \
CDD/rtc \
CDD/sbc \
INFRA/integration/src \
INFRA/rba_BswSrv/src \
INFRA/schm/src \
RTE/gen \
Targets/SPC5775B/LINK \
Targets/SPC5775B/MCAL/Gen/src \
Targets/SPC5775B/MCAL/integration/src \
Targets/SPC5775B/MCAL/modules/Adc/src \
Targets/SPC5775B/MCAL/modules/Can/src \
Targets/SPC5775B/MCAL/modules/Dio/src \
Targets/SPC5775B/MCAL/modules/Esci/src \
Targets/SPC5775B/MCAL/modules/Eth/src \
Targets/SPC5775B/MCAL/modules/EthIf/src \
Targets/SPC5775B/MCAL/modules/Fls/src \
Targets/SPC5775B/MCAL/modules/Gpt/src \
Targets/SPC5775B/MCAL/modules/MCan/src \
Targets/SPC5775B/MCAL/modules/Mcl/src \
Targets/SPC5775B/MCAL/modules/Mcu/src \
Targets/SPC5775B/MCAL/modules/Port/src \
Targets/SPC5775B/MCAL/modules/Pwm/src \
Targets/SPC5775B/MCAL/modules/Spi/src \
Targets/SPC5775B/RTAOS/output/src \

