/*
 * File: ECCR_Cal.c
 *
 * Code generated for Simulink model 'ECCR'.
 *
 * Company                        : DP
 * Author                         : 19952702426
 * Model version                  : 'EV31A-M1.05'
 * Simulink Coder version         : 8.9 (R2015b) 13-Aug-2015
 * C/C++ source code generated on : Mon Jun 08 15:47:51 2020
 *
 * Target selection: ert.tlc
 * Embedded hardware selection: Freescale->32-bit PowerPC
 * Code generation objective: MISRA C:2012 guidelines
 * Validation result: Not run
 */
 
#include "rtwtypes.h"
#include "ECCR_types.h"
 
#pragma section DATA ".cal_data"
/* Exported data definition */
volatile boolean_T CbECCR_CCU1BCL1817FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BCLSPN3072UReqOvrSwt_flg = 0;/* 电压需求 */
volatile boolean_T CbECCR_CCU1BCLSPN3073IReqOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BCLSPN3074ChgModeOvrSwt_flg = 0;/* 充电模式 */
volatile boolean_T CbECCR_CCU1BCP1812FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BCP1813FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BCPSPN2816UcellMaxPermitOvrSwt_flg = 0;/* 单体动力蓄电池最高允许充电电压 */
volatile boolean_T CbECCR_CCU1BCPSPN2817IMaxPermitOvrSwt_flg = 0;/* 最高允许充电电流 */
volatile boolean_T CbECCR_CCU1BCPSPN2818kWhNomOvrSwt_flg = 0;/* 动力蓄电池标称总能量 */
volatile boolean_T CbECCR_CCU1BCPSPN2819UMaxPermitOvrSwt_flg = 0;/* 最高允许充电总电压 */
volatile boolean_T CbECCR_CCU1BCPSPN2820TMaxPermitOvrSwt_flg = 0;/* 最高允许动力蓄电池温度 */
volatile boolean_T CbECCR_CCU1BCPSPN2821SOCOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BCPSPN2822UOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BCS1818FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BCSSPN3075UMeaOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BCSSPN3076IMeaOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BCSSPN3077UcellMaxGrpOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BCSSPN3077UcellMaxOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BCSSPN3078SOCOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BCSSPN3079TimeRemainOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BEMSPN3901TimeoutSPN25600x00OvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BEMSPN3902TimeoutSPN25600xAAOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BEMSPN3903TimeoutCTSCMLOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BEMSPN3904TimeoutCROOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BEMSPN3905TimeoutCCSOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BEMSPN3906TimeoutCSTOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BEMSPN3907TimeoutCSDOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BEMotherOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BHM1811FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BHMSPN2601UbatMaxPermitOvrSwt_flg = 0;/* 车端允许充电最高电压（用于绝缘检测） */
volatile boolean_T CbECCR_CCU1BRM1814FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BRM1815FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BRMSPN2565CommVerOvrSwt_flg = 0;/* 车端通讯协议版本 */
volatile boolean_T CbECCR_CCU1BRMSPN2566BatTypeOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BRMSPN2567CapNomOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BRMSPN2568UNomOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BRMSPN2569BatFactoryOvrSwt_flg = 0;/* 电池生产厂商名称（4位ASCII） */
volatile boolean_T CbECCR_CCU1BRMSPN2570PackSNOvrSwt_flg = 0;/* 电池模组编号（厂商自定义） */
volatile boolean_T CbECCR_CCU1BSD181BFAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSDSPN3601SOCFinalOvrSwt_flg = 0;/* 中止荷电状态SOC */
volatile boolean_T CbECCR_CCU1BSDSPN3602UcellMinOvrSwt_flg = 0;/* 动力蓄电池单体最低电压 */
volatile boolean_T CbECCR_CCU1BSDSPN3603UcellMaxOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSDSPN3604TMinOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSDSPN3605TMaxOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSM181AFAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSMSPN3085UcellMaxIndexOvrSwt_flg = 0;/* 最高单体动力蓄电池电压所在编号 */
volatile boolean_T CbECCR_CCU1BSMSPN3086TMaxOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSMSPN3087TMaxIndexOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSMSPN3088TMinOvrSwt_flg = 0;/* 最低动力蓄电池温度 */
volatile boolean_T CbECCR_CCU1BSMSPN3089TMinIndexOvrSwt_flg = 0;/* 最低动力蓄电池温度检测点编号 */
volatile boolean_T CbECCR_CCU1BSMSPN3090UcellWarnOvrSwt_flg = 0;/* 单体动力蓄电池电压 */
volatile boolean_T CbECCR_CCU1BSMSPN3091SOCWarnOvrSwt_flg = 0;/* 整车动力蓄电池荷电状态SOC */
volatile boolean_T CbECCR_CCU1BSMSPN3092IWarnOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSMSPN3093TWarnOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSMSPN3094IsoStateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSMSPN3095OutConnectorStateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSMSPN3096ChgEnableOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BST181CFAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSTSPN3511StopReasonCHGStopOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSTSPN3511StopReasonSOCOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSTSPN3511StopReasonUOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSTSPN3511StopReasonUcellOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSTSPN3512StopFaultBCUcompoOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSTSPN3512StopFaultCC2OvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSTSPN3512StopFaultChgCnntOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSTSPN3512StopFaultHVRelayOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSTSPN3512StopFaultIsoOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSTSPN3512StopFaultOtherOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSTSPN3512StopFaultOutCnntOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSTSPN3512StopFaultTOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSTSPN3513StopFaultIOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1BSTSPN3513StopFaultUOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CCS1819FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CCSSPN3081UOutOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CCSSPN3082IOutOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CCSSPN3083TimeChargedOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CCU12VSTATEOvrSwt_flg = 0;/* CCU22V状态 */
volatile boolean_T CbECCR_CCU1CCU24VSTATEOvrSwt_flg = 0;/* CCU24V状态 */
volatile boolean_T CbECCR_CCU1CCUCARCONNECTSTATEOvrSwt_flg = 0;/* 车辆是否反接 */
volatile boolean_T CbECCR_CCU1CCUCC1STATEOvrSwt_flg = 0;/* CC1状态 */
volatile boolean_T CbECCR_CCU1CCUDTCFailureTypeByteOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CCUDTCHighByteOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CCUDTCLowByteOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CCUGUNTEMP1STATEOvrSwt_flg = 0;/* 枪温度2状态 */
volatile boolean_T CbECCR_CCU1CCUGUNTEMP2STATEOvrSwt_flg = 0;/* 枪温度1状态 */
volatile boolean_T CbECCR_CCU1CCUGUNpositionOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CCUHVFuseVLTGOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CCUHVRelayOutVLTGOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CCUHVRelayintVLTGOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CCUHwVersionOvrSwt_flg = 0;
volatile uint8_T CbECCR_CCU1CCUHwVersionOvr_numb = 0U;
volatile boolean_T CbECCR_CCU1CCUISOCheckFinishOvrSwt_flg = 0;/* CCU ISO完成状态 */
volatile uint8_T CbECCR_CCU1CCUISOCheckFinishOvr_flg = 0U;/* CCU ISO完成状态 */
volatile boolean_T CbECCR_CCU1CCUISONegVoltOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CCUISOOvrSwt_flg = 0;/* CCU绝缘检测 */
volatile boolean_T CbECCR_CCU1CCUISOPosVoltOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CCUISOSTATEOvrSwt_flg = 0;/* CCU绝缘检测状态 */
volatile boolean_T CbECCR_CCU1CCUIndexOvrSwt_flg = 0;/* CCU编号 */
volatile boolean_T CbECCR_CCU1CCUK1K3STATEOvrSwt_flg = 0;/* K1继电器状态(K3) */
volatile boolean_T CbECCR_CCU1CCUK2K4STATEOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CCUPyroswitchCMDOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CCUSTATEOvrSwt_flg = 0;/* CCU工作状态 */
volatile boolean_T CbECCR_CCU1CCUShuntCurrentOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CCUSwVersionOvrSwt_flg = 0;
volatile uint8_T CbECCR_CCU1CCUSwVersionOvr_numb = 0U;
volatile boolean_T CbECCR_CCU1CCUSysStatAliveCounterOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CCUSysStatCheckSumOvrSwt_flg = 0;
volatile uint8_T CbECCR_CCU1CCUSysStatCheckSumOvr_numb = 0U;
volatile boolean_T CbECCR_CCU1CCUTEMP1OvrSwt_flg = 0;/* 枪端温度采集1 */
volatile boolean_T CbECCR_CCU1CCUTEMP2OvrSwt_flg = 0;/* 枪端温度采集2 */
volatile boolean_T CbECCR_CCU1CEMOtherOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CEMSPN3921TimeoutBRMOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CEMSPN3922TimeoutBCPOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CEMSPN3923TimeoutBROOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CEMSPN3924TimeoutBCSOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CEMSPN3925TimeoutBCLOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CEMSPN3926TimeoutBSTOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CEMSPN3927TimeoutBSDOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CHMSPN2600CommVerOvrSwt_flg = 0;/* 桩端通讯协议版本 */
volatile boolean_T CbECCR_CCU1CST181DFAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CSTSPN3521StopReasonAutoOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CSTSPN3521StopReasonBMSStopOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CSTSPN3521StopReasonFaultOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CSTSPN3521StopReasonManualOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CSTSPN3522StopFaultCHGCnntOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CSTSPN3522StopFaultDeliverOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CSTSPN3522StopFaultEmerStopOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CSTSPN3522StopFaultOtherOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CSTSPN3522StopFaultTCHGOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CSTSPN3522StopFaultTInterOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CSTSPN3523StopFaultMismatchOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CSTSPN3523StopFaultUOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1ChgBCLOvrSwt_flg = 0;
volatile uint8_T CbECCR_CCU1ChgBCLOvr_flg = 0U;
volatile boolean_T CbECCR_CCU1ChgBCPOvrSwt_flg = 0;
volatile uint8_T CbECCR_CCU1ChgBCPOvr_flg = 0U;
volatile boolean_T CbECCR_CCU1ChgBHMOvrSwt_flg = 0;
volatile uint8_T CbECCR_CCU1ChgBHMOvr_flg = 0U;
volatile boolean_T CbECCR_CCU1ChgBSTOvrSwt_flg = 0;
volatile uint8_T CbECCR_CCU1ChgBSTOvr_flg = 0U;
volatile boolean_T CbECCR_CCU1CrossNegStateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1CrossPosStateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1DTC18AAFAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1DirectNegStateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1DirectPosStateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1ELOCKSTATEOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1FUSE1STATEOvrSwt_flg = 0;/* 保险丝状态 */
volatile boolean_T CbECCR_CCU1FaultSevtyStatOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1HV1802FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1ISO1820FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1Sample1803FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1VIN1816FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1VINNum1OvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1VINNum2OvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1VINNum3OvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1VINNum4OvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1VINNum5OvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1VINNum6OvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1VINNum7OvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU1VINNumIndexOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BCL1817FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BCLSPN3072UReqOvrSwt_flg = 0;/* 电压需求 */
volatile boolean_T CbECCR_CCU2BCLSPN3073IReqOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BCLSPN3074ChgModeOvrSwt_flg = 0;/* 充电模式 */
volatile boolean_T CbECCR_CCU2BCP1812FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BCP1813FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BCPSPN2816UcellMaxPermitOvrSwt_flg = 0;/* 单体动力蓄电池最高允许充电电压 */
volatile boolean_T CbECCR_CCU2BCPSPN2817IMaxPermitOvrSwt_flg = 0;/* 最高允许充电电流 */
volatile boolean_T CbECCR_CCU2BCPSPN2818kWhNomOvrSwt_flg = 0;/* 动力蓄电池标称总能量 */
volatile boolean_T CbECCR_CCU2BCPSPN2819UMaxPermitOvrSwt_flg = 0;/* 最高允许充电总电压 */
volatile boolean_T CbECCR_CCU2BCPSPN2820TMaxPermitOvrSwt_flg = 0;/* 最高允许动力蓄电池温度 */
volatile boolean_T CbECCR_CCU2BCPSPN2821SOCOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BCPSPN2822UOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BCS1818FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BCSSPN3075UMeaOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BCSSPN3076IMeaOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BCSSPN3077UcellMaxGrpOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BCSSPN3077UcellMaxOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BCSSPN3078SOCOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BCSSPN3079TimeRemainOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BEMSPN3901TimeoutSPN25600x00OvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BEMSPN3902TimeoutSPN25600xAAOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BEMSPN3903TimeoutCTSCMLOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BEMSPN3904TimeoutCROOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BEMSPN3905TimeoutCCSOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BEMSPN3906TimeoutCSTOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BEMSPN3907TimeoutCSDOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BEMotherOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BHM1811FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BHMSPN2601UbatMaxPermitOvrSwt_flg = 0;/* 车端允许充电最高电压（用于绝缘检测） */
volatile boolean_T CbECCR_CCU2BRM1814FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BRM1815FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BRMSPN2565CommVerOvrSwt_flg = 0;/* 车端通讯协议版本 */
volatile boolean_T CbECCR_CCU2BRMSPN2566BatTypeOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BRMSPN2567CapNomOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BRMSPN2568UNomOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BRMSPN2569BatFactoryOvrSwt_flg = 0;/* 电池生产厂商名称（4位ASCII） */
volatile boolean_T CbECCR_CCU2BRMSPN2570PackSNOvrSwt_flg = 0;/* 电池模组编号（厂商自定义） */
volatile boolean_T CbECCR_CCU2BSD181BFAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSDSPN3601SOCFinalOvrSwt_flg = 0;/* 中止荷电状态SOC */
volatile boolean_T CbECCR_CCU2BSDSPN3602UcellMinOvrSwt_flg = 0;/* 动力蓄电池单体最低电压 */
volatile boolean_T CbECCR_CCU2BSDSPN3603UcellMaxOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSDSPN3604TMinOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSDSPN3605TMaxOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSM181AFAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSMSPN3085UcellMaxIndexOvrSwt_flg = 0;/* 最高单体动力蓄电池电压所在编号 */
volatile boolean_T CbECCR_CCU2BSMSPN3086TMaxOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSMSPN3087TMaxIndexOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSMSPN3088TMinOvrSwt_flg = 0;/* 最低动力蓄电池温度 */
volatile boolean_T CbECCR_CCU2BSMSPN3089TMinIndexOvrSwt_flg = 0;/* 最低动力蓄电池温度检测点编号 */
volatile boolean_T CbECCR_CCU2BSMSPN3090UcellWarnOvrSwt_flg = 0;/* 单体动力蓄电池电压 */
volatile boolean_T CbECCR_CCU2BSMSPN3091SOCWarnOvrSwt_flg = 0;/* 整车动力蓄电池荷电状态SOC */
volatile boolean_T CbECCR_CCU2BSMSPN3092IWarnOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSMSPN3093TWarnOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSMSPN3094IsoStateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSMSPN3095OutConnectorStateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSMSPN3096ChgEnableOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BST181CFAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSTSPN3511StopReasonCHGStopOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSTSPN3511StopReasonSOCOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSTSPN3511StopReasonUOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSTSPN3511StopReasonUcellOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSTSPN3512StopFaultBCUcompoOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSTSPN3512StopFaultCC2OvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSTSPN3512StopFaultChgCnntOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSTSPN3512StopFaultHVRelayOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSTSPN3512StopFaultIsoOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSTSPN3512StopFaultOtherOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSTSPN3512StopFaultOutCnntOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSTSPN3512StopFaultTOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSTSPN3513StopFaultIOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2BSTSPN3513StopFaultUOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CCS1819FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CCSSPN3081UOutOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CCSSPN3082IOutOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CCSSPN3083TimeChargedOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CCU22VSTATEOvrSwt_flg = 0;/* CCU22V状态 */
volatile boolean_T CbECCR_CCU2CCU24VSTATEOvrSwt_flg = 0;/* CCU24V状态 */
volatile boolean_T CbECCR_CCU2CCUCARCONNECTSTATEOvrSwt_flg = 0;/* 车辆是否反接 */
volatile boolean_T CbECCR_CCU2CCUCC1STATEOvrSwt_flg = 0;/* CC1状态 */
volatile boolean_T CbECCR_CCU2CCUDTCFailureTypeByteOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CCUDTCHighByteOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CCUDTCLowByteOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CCUGUNTEMP1STATEOvrSwt_flg = 0;/* 枪温度2状态 */
volatile boolean_T CbECCR_CCU2CCUGUNTEMP2STATEOvrSwt_flg = 0;/* 枪温度1状态 */
volatile boolean_T CbECCR_CCU2CCUGUNpositionOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CCUHVFuseVLTGOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CCUHVRelayOutVLTGOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CCUHVRelayintVLTGOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CCUHwVersionOvrSwt_flg = 0;
volatile uint8_T CbECCR_CCU2CCUHwVersionOvr_numb = 0U;
volatile boolean_T CbECCR_CCU2CCUISOCheckFinishOvrSwt_flg = 0;/* CCU ISO完成状态 */
volatile uint8_T CbECCR_CCU2CCUISOCheckFinishOvr_flg = 0U;/* CCU ISO完成状态 */
volatile boolean_T CbECCR_CCU2CCUISONegVoltOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CCUISOOvrSwt_flg = 0;/* CCU绝缘检测 */
volatile boolean_T CbECCR_CCU2CCUISOPosVoltOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CCUISOSTATEOvrSwt_flg = 0;/* CCU绝缘检测状态 */
volatile boolean_T CbECCR_CCU2CCUIndexOvrSwt_flg = 0;/* CCU编号 */
volatile boolean_T CbECCR_CCU2CCUK1K3STATEOvrSwt_flg = 0;/* K1继电器状态(K3) */
volatile boolean_T CbECCR_CCU2CCUK2K4STATEOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CCUPyroswitchCMDOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CCUSTATEOvrSwt_flg = 0;/* CCU工作状态 */
volatile boolean_T CbECCR_CCU2CCUShuntCurrentOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CCUSwVersionOvrSwt_flg = 0;
volatile uint8_T CbECCR_CCU2CCUSwVersionOvr_numb = 0U;
volatile boolean_T CbECCR_CCU2CCUSysStatAliveCounterOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CCUSysStatCheckSumOvrSwt_flg = 0;
volatile uint8_T CbECCR_CCU2CCUSysStatCheckSumOvr_numb = 0U;
volatile boolean_T CbECCR_CCU2CCUTEMP1OvrSwt_flg = 0;/* 枪端温度采集1 */
volatile boolean_T CbECCR_CCU2CCUTEMP2OvrSwt_flg = 0;/* 枪端温度采集2 */
volatile boolean_T CbECCR_CCU2CEMOtherOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CEMSPN3921TimeoutBRMOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CEMSPN3922TimeoutBCPOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CEMSPN3923TimeoutBROOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CEMSPN3924TimeoutBCSOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CEMSPN3925TimeoutBCLOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CEMSPN3926TimeoutBSTOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CEMSPN3927TimeoutBSDOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CHMSPN2600CommVerOvrSwt_flg = 0;/* 桩端通讯协议版本 */
volatile boolean_T CbECCR_CCU2CST181DFAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CSTSPN3521StopReasonAutoOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CSTSPN3521StopReasonBMSStopOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CSTSPN3521StopReasonFaultOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CSTSPN3521StopReasonManualOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CSTSPN3522StopFaultCHGCnntOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CSTSPN3522StopFaultDeliverOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CSTSPN3522StopFaultEmerStopOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CSTSPN3522StopFaultOtherOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CSTSPN3522StopFaultTCHGOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CSTSPN3522StopFaultTInterOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CSTSPN3523StopFaultMismatchOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CSTSPN3523StopFaultUOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2ChgBCLOvrSwt_flg = 0;
volatile uint8_T CbECCR_CCU2ChgBCLOvr_flg = 0U;
volatile boolean_T CbECCR_CCU2ChgBCPOvrSwt_flg = 0;
volatile uint8_T CbECCR_CCU2ChgBCPOvr_flg = 0U;
volatile boolean_T CbECCR_CCU2ChgBHMOvrSwt_flg = 0;
volatile uint8_T CbECCR_CCU2ChgBHMOvr_flg = 0U;
volatile boolean_T CbECCR_CCU2ChgBSTOvrSwt_flg = 0;
volatile uint8_T CbECCR_CCU2ChgBSTOvr_flg = 0U;
volatile boolean_T CbECCR_CCU2CrossNegStateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2CrossPosStateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2DTC18AAFAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2DirectNegStateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2DirectPosStateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2ELOCKSTATEOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2FUSE1STATEOvrSwt_flg = 0;/* 保险丝状态 */
volatile boolean_T CbECCR_CCU2FaultSevtyStatOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2HV1802FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2ISO1820FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2Sample1803FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2VIN1816FAF2hUpdateOvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2VINNum1OvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2VINNum2OvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2VINNum3OvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2VINNum4OvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2VINNum5OvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2VINNum6OvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2VINNum7OvrSwt_flg = 0;
volatile boolean_T CbECCR_CCU2VINNumIndexOvrSwt_flg = 0;
volatile boolean_T CbECCR_GunAMaxPwrOvrSwt_flg = 0;
volatile boolean_T CcECCR_CCU1BCL1817FAF2hUpdateOvr_flg = 0;
volatile real32_T CcECCR_CCU1BCLSPN3072UReqOvr_V = 0.0F;/* 电压需求 */
volatile real32_T CcECCR_CCU1BCLSPN3073IReqOvr_A = 0.0F;
volatile uint8_T CcECCR_CCU1BCLSPN3074ChgModeOvr_enum = 0U;/* 充电模式 */
volatile boolean_T CcECCR_CCU1BCP1812FAF2hUpdateOvr_flg = 0;
volatile boolean_T CcECCR_CCU1BCP1813FAF2hUpdateOvr_flg = 0;
volatile uint16_T CcECCR_CCU1BCPSPN2816UcellMaxPermitOvr_V = 0U;/* 单体动力蓄电池最高允许充电电压 */
volatile real32_T CcECCR_CCU1BCPSPN2817IMaxPermitOvr_A = 0.0F;/* 最高允许充电电流 */
volatile real32_T CcECCR_CCU1BCPSPN2818kWhNomOvr_Kwh = 0.0F;/* 动力蓄电池标称总能量 */
volatile real32_T CcECCR_CCU1BCPSPN2819UMaxPermitOvr_V = 0.0F;/* 最高允许充电总电压 */
volatile real32_T CcECCR_CCU1BCPSPN2820TMaxPermitOvr_C = 0.0F;/* 最高允许动力蓄电池温度 */
volatile real32_T CcECCR_CCU1BCPSPN2821SOCOvr_Pct = 0.0F;
volatile real32_T CcECCR_CCU1BCPSPN2822UOvr_V = 0.0F;
volatile boolean_T CcECCR_CCU1BCS1818FAF2hUpdateOvr_flg = 0;
volatile real32_T CcECCR_CCU1BCSSPN3075UMeaOvr_V = 0.0F;
volatile real32_T CcECCR_CCU1BCSSPN3076IMeaOvr_A = 0.0F;
volatile uint16_T CcECCR_CCU1BCSSPN3077UcellMaxOvr_V = 0U;
volatile uint8_T CcECCR_CCU1BCSSPN3078SOCOvr_Pct = 0U;
volatile uint16_T CcECCR_CCU1BCSSPN3079TimeRemainOvr_min = 0U;
volatile uint8_T CcECCR_CCU1BEMSPN3901TimeoutSPN25600x00Ovr_enum = 0U;
volatile uint8_T CcECCR_CCU1BEMSPN3902TimeoutSPN25600xAAOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1BEMSPN3903TimeoutCTSCMLOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1BEMSPN3904TimeoutCROOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1BEMSPN3905TimeoutCCSOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1BEMSPN3906TimeoutCSTOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1BEMSPN3907TimeoutCSDOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1BEMotherOvr_enum = 0U;
volatile boolean_T CcECCR_CCU1BHM1811FAF2hUpdateOvr_flg = 0;
volatile real32_T CcECCR_CCU1BHMSPN2601UbatMaxPermitOvr_V = 0.0F;/* 车端允许充电最高电压（用于绝缘检测） */
volatile boolean_T CcECCR_CCU1BRM1814FAF2hUpdateOvr_flg = 0;
volatile boolean_T CcECCR_CCU1BRM1815FAF2hUpdateOvr_flg = 0;
volatile uint32_T CcECCR_CCU1BRMSPN2565CommVerOvr_numb = 0U;/* 车端通讯协议版本 */
volatile real32_T CcECCR_CCU1BRMSPN2567CapNomOvr_Ah = 0.0F;
volatile real32_T CcECCR_CCU1BRMSPN2568UNomOvr_V = 0.0F;
volatile uint32_T CcECCR_CCU1BRMSPN2569BatFactoryOvr_numb = 0U;/* 电池生产厂商名称（4位ASCII） */
volatile uint32_T CcECCR_CCU1BRMSPN2570PackSNOvr_numb = 0U;/* 电池模组编号（厂商自定义） */
volatile boolean_T CcECCR_CCU1BSD181BFAF2hUpdateOvr_flg = 0;
volatile uint8_T CcECCR_CCU1BSDSPN3601SOCFinalOvr_Pct = 0U;/* 中止荷电状态SOC */
volatile uint16_T CcECCR_CCU1BSDSPN3602UcellMinOvr_V = 0U;/* 动力蓄电池单体最低电压 */
volatile uint16_T CcECCR_CCU1BSDSPN3603UcellMaxOvr_V = 0U;
volatile real32_T CcECCR_CCU1BSDSPN3604TMinOvr_C = 0.0F;
volatile real32_T CcECCR_CCU1BSDSPN3605TMaxOvr_C = 0.0F;
volatile boolean_T CcECCR_CCU1BSM181AFAF2hUpdateOvr_flg = 0;
volatile real32_T CcECCR_CCU1BSMSPN3086TMaxOvr_C = 0.0F;
volatile real32_T CcECCR_CCU1BSMSPN3088TMinOvr_C = 0.0F;/* 最低动力蓄电池温度 */
volatile uint8_T CcECCR_CCU1BSMSPN3089TMinIndexOvr_enum = 0U;/* 最低动力蓄电池温度检测点编号 */
volatile boolean_T CcECCR_CCU1BST181CFAF2hUpdateOvr_flg = 0;
volatile uint8_T CcECCR_CCU1BSTSPN3511StopReasonCHGStopOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1BSTSPN3511StopReasonSOCOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1BSTSPN3511StopReasonUOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1BSTSPN3511StopReasonUcellOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1BSTSPN3512StopFaultBCUcompoOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1BSTSPN3512StopFaultCC2Ovr_enum = 0U;
volatile uint8_T CcECCR_CCU1BSTSPN3512StopFaultChgCnntOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1BSTSPN3512StopFaultHVRelayOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1BSTSPN3512StopFaultIsoOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1BSTSPN3512StopFaultOtherOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1BSTSPN3512StopFaultOutCnntOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1BSTSPN3512StopFaultTOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1BSTSPN3513StopFaultIOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1BSTSPN3513StopFaultUOvr_enum = 0U;
volatile boolean_T CcECCR_CCU1CCS1819FAF2hUpdateOvr_flg = 0;
volatile real32_T CcECCR_CCU1CCSSPN3081UOutOvr_V = 0.0F;
volatile real32_T CcECCR_CCU1CCSSPN3082IOutOvr_A = 0.0F;
volatile uint16_T CcECCR_CCU1CCSSPN3083TimeChargedOvr_Min = 0U;
volatile uint8_T CcECCR_CCU1CCUDTCFailureTypeByteOvr_numb = 0U;
volatile uint8_T CcECCR_CCU1CCUDTCHighByteOvr_numb = 0U;
volatile uint8_T CcECCR_CCU1CCUDTCLowByteOvr_numb = 0U;
volatile uint8_T CcECCR_CCU1CCUGUNTEMP1STATEOvr_enum = 0U;/* 枪温度2状态 */
volatile uint8_T CcECCR_CCU1CCUGUNTEMP2STATEOvr_enum = 0U;/* 枪温度1状态 */
volatile real32_T CcECCR_CCU1CCUHVFuseVLTGOvr_V = 0.0F;
volatile real32_T CcECCR_CCU1CCUHVRelayOutVLTGOvr_V = 0.0F;
volatile real32_T CcECCR_CCU1CCUHVRelayintVLTGOvr_V = 0.0F;
volatile uint16_T CcECCR_CCU1CCUISONegVoltOvr_Kohm = 0U;
volatile real32_T CcECCR_CCU1CCUISONegVoltOvr_V = 0.0F;
volatile uint16_T CcECCR_CCU1CCUISOOvr_Kohm = 0U;/* CCU绝缘检测 */
volatile uint16_T CcECCR_CCU1CCUISOPosVoltOvr_Kohm = 0U;
volatile real32_T CcECCR_CCU1CCUISOPosVoltOvr_V = 0.0F;
volatile real32_T CcECCR_CCU1CCUShuntCurrentOvr_A = 0.0F;
volatile uint8_T CcECCR_CCU1CCUSysStatAliveCounterOvr_numb = 0U;
volatile real32_T CcECCR_CCU1CCUTEMP1Ovr_C = 0.0F;/* 枪端温度采集1 */
volatile real32_T CcECCR_CCU1CCUTEMP2Ovr_C = 0.0F;/* 枪端温度采集2 */
volatile uint32_T CcECCR_CCU1CHMSPN2600CommVerOvr_numb = 0U;/* 桩端通讯协议版本 */
volatile boolean_T CcECCR_CCU1CST181DFAF2hUpdateOvr_flg = 0;
volatile uint8_T CcECCR_CCU1CrossNegStateOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1CrossPosStateOvr_enum = 0U;
volatile boolean_T CcECCR_CCU1DTC18AAFAF2hUpdateOvr_flg = 0;
volatile uint8_T CcECCR_CCU1DirectNegStateOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1DirectPosStateOvr_enum = 0U;
volatile uint8_T CcECCR_CCU1ELOCKSTATEOvr_enum = 0U;
volatile boolean_T CcECCR_CCU1HV1802FAF2hUpdateOvr_flg = 0;
volatile boolean_T CcECCR_CCU1ISO1820FAF2hUpdateOvr_flg = 0;
volatile boolean_T CcECCR_CCU1Sample1803FAF2hUpdateOvr_flg = 0;
volatile boolean_T CcECCR_CCU1VIN1816FAF2hUpdateOvr_flg = 0;
volatile uint8_T CcECCR_CCU1VINNum1Ovr_numb = 0U;
volatile uint8_T CcECCR_CCU1VINNum2Ovr_numb = 0U;
volatile uint8_T CcECCR_CCU1VINNum3Ovr_numb = 0U;
volatile uint8_T CcECCR_CCU1VINNum4Ovr_numb = 0U;
volatile uint8_T CcECCR_CCU1VINNum5Ovr_numb = 0U;
volatile uint8_T CcECCR_CCU1VINNum6Ovr_numb = 0U;
volatile uint8_T CcECCR_CCU1VINNum7Ovr_numb = 0U;
volatile uint8_T CcECCR_CCU1VINNumIndexOvr_numb = 0U;
volatile boolean_T CcECCR_CCU2BCL1817FAF2hUpdateOvr_flg = 0;
volatile real32_T CcECCR_CCU2BCLSPN3072UReqOvr_V = 0.0F;/* 电压需求 */
volatile real32_T CcECCR_CCU2BCLSPN3073IReqOvr_A = 0.0F;
volatile uint8_T CcECCR_CCU2BCLSPN3074ChgModeOvr_enum = 0U;/* 充电模式 */
volatile boolean_T CcECCR_CCU2BCP1812FAF2hUpdateOvr_flg = 0;
volatile boolean_T CcECCR_CCU2BCP1813FAF2hUpdateOvr_flg = 0;
volatile uint16_T CcECCR_CCU2BCPSPN2816UcellMaxPermitOvr_V = 0U;/* 单体动力蓄电池最高允许充电电压 */
volatile real32_T CcECCR_CCU2BCPSPN2817IMaxPermitOvr_A = 0.0F;/* 最高允许充电电流 */
volatile real32_T CcECCR_CCU2BCPSPN2818kWhNomOvr_Kwh = 0.0F;/* 动力蓄电池标称总能量 */
volatile real32_T CcECCR_CCU2BCPSPN2819UMaxPermitOvr_V = 0.0F;/* 最高允许充电总电压 */
volatile real32_T CcECCR_CCU2BCPSPN2820TMaxPermitOvr_C = 0.0F;/* 最高允许动力蓄电池温度 */
volatile real32_T CcECCR_CCU2BCPSPN2821SOCOvr_Pct = 0.0F;
volatile real32_T CcECCR_CCU2BCPSPN2822UOvr_V = 0.0F;
volatile boolean_T CcECCR_CCU2BCS1818FAF2hUpdateOvr_flg = 0;
volatile real32_T CcECCR_CCU2BCSSPN3075UMeaOvr_V = 0.0F;
volatile real32_T CcECCR_CCU2BCSSPN3076IMeaOvr_A = 0.0F;
volatile uint16_T CcECCR_CCU2BCSSPN3077UcellMaxOvr_V = 0U;
volatile uint8_T CcECCR_CCU2BCSSPN3078SOCOvr_Pct = 0U;
volatile uint16_T CcECCR_CCU2BCSSPN3079TimeRemainOvr_min = 0U;
volatile uint8_T CcECCR_CCU2BEMSPN3901TimeoutSPN25600x00Ovr_enum = 0U;
volatile uint8_T CcECCR_CCU2BEMSPN3902TimeoutSPN25600xAAOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2BEMSPN3903TimeoutCTSCMLOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2BEMSPN3904TimeoutCROOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2BEMSPN3905TimeoutCCSOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2BEMSPN3906TimeoutCSTOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2BEMSPN3907TimeoutCSDOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2BEMotherOvr_enum = 0U;
volatile boolean_T CcECCR_CCU2BHM1811FAF2hUpdateOvr_flg = 0;
volatile real32_T CcECCR_CCU2BHMSPN2601UbatMaxPermitOvr_V = 0.0F;/* 车端允许充电最高电压（用于绝缘检测） */
volatile boolean_T CcECCR_CCU2BRM1814FAF2hUpdateOvr_flg = 0;
volatile boolean_T CcECCR_CCU2BRM1815FAF2hUpdateOvr_flg = 0;
volatile uint32_T CcECCR_CCU2BRMSPN2565CommVerOvr_numb = 0U;/* 车端通讯协议版本 */
volatile real32_T CcECCR_CCU2BRMSPN2567CapNomOvr_Ah = 0.0F;
volatile real32_T CcECCR_CCU2BRMSPN2568UNomOvr_V = 0.0F;
volatile uint32_T CcECCR_CCU2BRMSPN2569BatFactoryOvr_numb = 0U;/* 电池生产厂商名称（4位ASCII） */
volatile uint32_T CcECCR_CCU2BRMSPN2570PackSNOvr_numb = 0U;/* 电池模组编号（厂商自定义） */
volatile boolean_T CcECCR_CCU2BSD181BFAF2hUpdateOvr_flg = 0;
volatile uint8_T CcECCR_CCU2BSDSPN3601SOCFinalOvr_Pct = 0U;/* 中止荷电状态SOC */
volatile uint16_T CcECCR_CCU2BSDSPN3602UcellMinOvr_V = 0U;/* 动力蓄电池单体最低电压 */
volatile uint16_T CcECCR_CCU2BSDSPN3603UcellMaxOvr_V = 0U;
volatile real32_T CcECCR_CCU2BSDSPN3604TMinOvr_C = 0.0F;
volatile real32_T CcECCR_CCU2BSDSPN3605TMaxOvr_C = 0.0F;
volatile boolean_T CcECCR_CCU2BSM181AFAF2hUpdateOvr_flg = 0;
volatile real32_T CcECCR_CCU2BSMSPN3086TMaxOvr_C = 0.0F;
volatile real32_T CcECCR_CCU2BSMSPN3088TMinOvr_C = 0.0F;/* 最低动力蓄电池温度 */
volatile uint8_T CcECCR_CCU2BSMSPN3089TMinIndexOvr_enum = 0U;/* 最低动力蓄电池温度检测点编号 */
volatile boolean_T CcECCR_CCU2BST181CFAF2hUpdateOvr_flg = 0;
volatile uint8_T CcECCR_CCU2BSTSPN3511StopReasonCHGStopOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2BSTSPN3511StopReasonSOCOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2BSTSPN3511StopReasonUOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2BSTSPN3511StopReasonUcellOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2BSTSPN3512StopFaultBCUcompoOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2BSTSPN3512StopFaultCC2Ovr_enum = 0U;
volatile uint8_T CcECCR_CCU2BSTSPN3512StopFaultChgCnntOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2BSTSPN3512StopFaultHVRelayOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2BSTSPN3512StopFaultIsoOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2BSTSPN3512StopFaultOtherOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2BSTSPN3512StopFaultOutCnntOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2BSTSPN3512StopFaultTOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2BSTSPN3513StopFaultIOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2BSTSPN3513StopFaultUOvr_enum = 0U;
volatile boolean_T CcECCR_CCU2CCS1819FAF2hUpdateOvr_flg = 0;
volatile real32_T CcECCR_CCU2CCSSPN3081UOutOvr_V = 0.0F;
volatile real32_T CcECCR_CCU2CCSSPN3082IOutOvr_A = 0.0F;
volatile uint16_T CcECCR_CCU2CCSSPN3083TimeChargedOvr_Min = 0U;
volatile uint8_T CcECCR_CCU2CCUDTCFailureTypeByteOvr_numb = 0U;
volatile uint8_T CcECCR_CCU2CCUDTCHighByteOvr_numb = 0U;
volatile uint8_T CcECCR_CCU2CCUDTCLowByteOvr_numb = 0U;
volatile uint8_T CcECCR_CCU2CCUGUNTEMP1STATEOvr_enum = 0U;/* 枪温度2状态 */
volatile uint8_T CcECCR_CCU2CCUGUNTEMP2STATEOvr_enum = 0U;/* 枪温度1状态 */
volatile real32_T CcECCR_CCU2CCUHVFuseVLTGOvr_V = 0.0F;
volatile real32_T CcECCR_CCU2CCUHVRelayOutVLTGOvr_V = 0.0F;
volatile real32_T CcECCR_CCU2CCUHVRelayintVLTGOvr_V = 0.0F;
volatile uint16_T CcECCR_CCU2CCUISONegVoltOvr_Kohm = 0U;
volatile real32_T CcECCR_CCU2CCUISONegVoltOvr_V = 0.0F;
volatile uint16_T CcECCR_CCU2CCUISOOvr_Kohm = 0U;/* CCU绝缘检测 */
volatile uint16_T CcECCR_CCU2CCUISOPosVoltOvr_Kohm = 0U;
volatile real32_T CcECCR_CCU2CCUISOPosVoltOvr_V = 0.0F;
volatile real32_T CcECCR_CCU2CCUShuntCurrentOvr_A = 0.0F;
volatile uint8_T CcECCR_CCU2CCUSysStatAliveCounterOvr_numb = 0U;
volatile real32_T CcECCR_CCU2CCUTEMP1Ovr_C = 0.0F;/* 枪端温度采集1 */
volatile real32_T CcECCR_CCU2CCUTEMP2Ovr_C = 0.0F;/* 枪端温度采集2 */
volatile uint32_T CcECCR_CCU2CHMSPN2600CommVerOvr_numb = 0U;/* 桩端通讯协议版本 */
volatile boolean_T CcECCR_CCU2CST181DFAF2hUpdateOvr_flg = 0;
volatile uint8_T CcECCR_CCU2CrossNegStateOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2CrossPosStateOvr_enum = 0U;
volatile boolean_T CcECCR_CCU2DTC18AAFAF2hUpdateOvr_flg = 0;
volatile uint8_T CcECCR_CCU2DirectNegStateOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2DirectPosStateOvr_enum = 0U;
volatile uint8_T CcECCR_CCU2ELOCKSTATEOvr_enum = 0U;
volatile boolean_T CcECCR_CCU2HV1802FAF2hUpdateOvr_flg = 0;
volatile boolean_T CcECCR_CCU2ISO1820FAF2hUpdateOvr_flg = 0;
volatile boolean_T CcECCR_CCU2Sample1803FAF2hUpdateOvr_flg = 0;
volatile boolean_T CcECCR_CCU2VIN1816FAF2hUpdateOvr_flg = 0;
volatile uint8_T CcECCR_CCU2VINNum1Ovr_numb = 0U;
volatile uint8_T CcECCR_CCU2VINNum2Ovr_numb = 0U;
volatile uint8_T CcECCR_CCU2VINNum3Ovr_numb = 0U;
volatile uint8_T CcECCR_CCU2VINNum4Ovr_numb = 0U;
volatile uint8_T CcECCR_CCU2VINNum5Ovr_numb = 0U;
volatile uint8_T CcECCR_CCU2VINNum6Ovr_numb = 0U;
volatile uint8_T CcECCR_CCU2VINNum7Ovr_numb = 0U;
volatile uint8_T CcECCR_CCU2VINNumIndexOvr_numb = 0U;
volatile real32_T CcECCR_GunAMaxPwrOvr_kw = 0.0F;
volatile uint8_T CeECCR_CCU1BCSSPN3077UcellMaxGrpOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1BRMSPN2566BatTypeOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1BSMSPN3085UcellMaxIndexOvr_enum = 0U;/* 最高单体动力蓄电池电压所在编号 */
volatile uint8_T CeECCR_CCU1BSMSPN3087TMaxIndexOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1BSMSPN3090UcellWarnOvr_enum = 0U;/* 单体动力蓄电池电压 */
volatile uint8_T CeECCR_CCU1BSMSPN3091SOCWarnOvr_enum = 0U;/* 整车动力蓄电池荷电状态SOC */
volatile uint8_T CeECCR_CCU1BSMSPN3092IWarnOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1BSMSPN3093TWarnOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1BSMSPN3094IsoStateOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1BSMSPN3095OutConnectorStateOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1BSMSPN3096ChgEnableOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CCU12VSTATEOvr_enum = 0U;/* CCU22V状态 */
volatile uint8_T CeECCR_CCU1CCU24VSTATEOvr_enum = 0U;/* CCU24V状态 */
volatile uint8_T CeECCR_CCU1CCUCARCONNECTSTATEOvr_enum = 0U;/* 车辆是否反接 */
volatile uint8_T CeECCR_CCU1CCUCC1STATEOvr_enum = 0U;/* CC1状态 */
volatile uint8_T CeECCR_CCU1CCUGUNpositionOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CCUISOSTATEOvr_enum = 0U;/* CCU绝缘检测状态 */
volatile uint8_T CeECCR_CCU1CCUIndexOvr_enum = 0U;/* CCU编号 */
volatile uint8_T CeECCR_CCU1CCUK1K3STATEOvr_enum = 0U;/* K1继电器状态(K3) */
volatile uint8_T CeECCR_CCU1CCUK2K4STATEOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CCUPyroswitchCMDOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CCUSTATEOvr_enum = 0U;/* CCU工作状态 */
volatile uint8_T CeECCR_CCU1CEMOtherOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CEMSPN3921TimeoutBRMOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CEMSPN3922TimeoutBCPOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CEMSPN3923TimeoutBROOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CEMSPN3924TimeoutBCSOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CEMSPN3925TimeoutBCLOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CEMSPN3926TimeoutBSTOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CEMSPN3927TimeoutBSDOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CSTSPN3521StopReasonAutoOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CSTSPN3521StopReasonBMSStopOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CSTSPN3521StopReasonFaultOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CSTSPN3521StopReasonManualOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CSTSPN3522StopFaultCHGCnntOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CSTSPN3522StopFaultDeliverOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CSTSPN3522StopFaultEmerStopOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CSTSPN3522StopFaultOtherOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CSTSPN3522StopFaultTCHGOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CSTSPN3522StopFaultTInterOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CSTSPN3523StopFaultMismatchOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1CSTSPN3523StopFaultUOvr_enum = 0U;
volatile uint8_T CeECCR_CCU1FUSE1STATEOvr_enum = 0U;/* 保险丝状态 */
volatile uint8_T CeECCR_CCU1FaultSevtyStatOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2BCSSPN3077UcellMaxGrpOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2BRMSPN2566BatTypeOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2BSMSPN3085UcellMaxIndexOvr_enum = 0U;/* 最高单体动力蓄电池电压所在编号 */
volatile uint8_T CeECCR_CCU2BSMSPN3087TMaxIndexOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2BSMSPN3090UcellWarnOvr_enum = 0U;/* 单体动力蓄电池电压 */
volatile uint8_T CeECCR_CCU2BSMSPN3091SOCWarnOvr_enum = 0U;/* 整车动力蓄电池荷电状态SOC */
volatile uint8_T CeECCR_CCU2BSMSPN3092IWarnOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2BSMSPN3093TWarnOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2BSMSPN3094IsoStateOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2BSMSPN3095OutConnectorStateOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2BSMSPN3096ChgEnableOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CCU22VSTATEOvr_enum = 0U;/* CCU22V状态 */
volatile uint8_T CeECCR_CCU2CCU24VSTATEOvr_enum = 0U;/* CCU24V状态 */
volatile uint8_T CeECCR_CCU2CCUCARCONNECTSTATEOvr_enum = 0U;/* 车辆是否反接 */
volatile uint8_T CeECCR_CCU2CCUCC1STATEOvr_enum = 0U;/* CC1状态 */
volatile uint8_T CeECCR_CCU2CCUGUNpositionOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CCUISOSTATEOvr_enum = 0U;/* CCU绝缘检测状态 */
volatile uint8_T CeECCR_CCU2CCUIndexOvr_enum = 0U;/* CCU编号 */
volatile uint8_T CeECCR_CCU2CCUK1K3STATEOvr_enum = 0U;/* K1继电器状态(K3) */
volatile uint8_T CeECCR_CCU2CCUK2K4STATEOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CCUPyroswitchCMDOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CCUSTATEOvr_enum = 0U;/* CCU工作状态 */
volatile uint8_T CeECCR_CCU2CEMOtherOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CEMSPN3921TimeoutBRMOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CEMSPN3922TimeoutBCPOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CEMSPN3923TimeoutBROOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CEMSPN3924TimeoutBCSOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CEMSPN3925TimeoutBCLOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CEMSPN3926TimeoutBSTOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CEMSPN3927TimeoutBSDOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CSTSPN3521StopReasonAutoOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CSTSPN3521StopReasonBMSStopOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CSTSPN3521StopReasonFaultOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CSTSPN3521StopReasonManualOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CSTSPN3522StopFaultCHGCnntOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CSTSPN3522StopFaultDeliverOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CSTSPN3522StopFaultEmerStopOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CSTSPN3522StopFaultOtherOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CSTSPN3522StopFaultTCHGOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CSTSPN3522StopFaultTInterOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CSTSPN3523StopFaultMismatchOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2CSTSPN3523StopFaultUOvr_enum = 0U;
volatile uint8_T CeECCR_CCU2FUSE1STATEOvr_enum = 0U;/* 保险丝状态 */
volatile uint8_T CeECCR_CCU2FaultSevtyStatOvr_enum = 0U;
volatile boolean_T GbECCR_GunBMaxPwrOvrSwt_flg = 0;
volatile real32_T GcECCR_GunBMaxPwrOvr_kw = 0.0F;
#pragma section DATA
/*
 * File trailer for generated code.
 *
 * [EOF]
 */
